const render = require("json-templater/string");
const { writeFileSync } = require("fs");
var endOfLine = require("os").EOL;

const template = `/* Automatically generated by demo.js */
{{header}}

{{footer}}
`;
const header = [];
const footer = [];

for (let index = 0; index < 10; index++) {
  header[index] = `console.log("header-${index}")`;
  footer[index] = `console.log("footer-${index}")`;
}

const code = render(template, {
  header: header.join(";" + endOfLine),
  footer: footer.join(";" + endOfLine),
});
writeFileSync("./index.js", code);
