/* Automatically generated by demo.js */
console.log("header-0");
console.log("header-1");
console.log("header-2");
console.log("header-3");
console.log("header-4");
console.log("header-5");
console.log("header-6");
console.log("header-7");
console.log("header-8");
console.log("header-9")

console.log("footer-0");
console.log("footer-1");
console.log("footer-2");
console.log("footer-3");
console.log("footer-4");
console.log("footer-5");
console.log("footer-6");
console.log("footer-7");
console.log("footer-8");
console.log("footer-9")
